apps/auth_shop/urls.py
from django.urls import path
from .views import Login
from .views import Login, CreateUserView

app_name = "auth_shop"

urlpatterns = [
  path('', Login.as_view(), name="login"),
  path('create/', CreateUserView.as_view(), name="create"),
]

apps/blog/urls.py
from django.urls import path
from .views import ViewBlog, ViewBlogSingle

app_name = 'blog'

urlpatterns = [
   path('', ViewBlog.as_view(), name='blog'),
   path('', ViewBlogSingle.as_view(), name='blog-single'),
]

apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
   path('', views.view_cart, name='view_cart'),
   path('update_item/<int:item_id>/', views.update_item, name='update_item'),
   path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
   path('checkout/', views.checkout, name='checkout'),
]

apps/cart_shop/urls.py
from django.urls import path
from .views import ViewCart, ViewWishlist, ViewCartAdd, ViewWishAdd

app_name = 'cart_shop'


urlpatterns = [
   path('cart/', ViewCart.as_view(), name='cart'),
   path('cart_add/<int:product_id>', ViewCartAdd.as_view(), name='add_to_cart'),
   path('wishlist/', ViewWishlist.as_view(), name='wishlist'),
   path('wishlist_add/<int:product_id>', ViewWishAdd.as_view(), name='wishlist_add'),
]

apps/checkout/urls.py
from django.urls import path
from .views import ViewCheckout

app_name = 'checkout'


urlpatterns = [
   path('', ViewCheckout.as_view(), name='checkout'),
]

apps/common/urls.py
from django.urls import path

from .views import CurrentDateView, IndexView

urlpatterns = [
   path('datetime/', CurrentDateView.as_view()),
   path('', IndexView.as_view())
]

apps/common_new/urls.py
from django.urls import path

from .views import HelloView

urlpatterns = [
   path('hello/', HelloView.as_view()),
]

apps/home/urls.py
from django.urls import path

from .views import IndexShopView, IndexShopAboutView, IndexShopContactView

app_name = 'home'

urlpatterns = [
   path('', IndexShopView.as_view(), name='index'),
   path('about/', IndexShopAboutView.as_view(), name='about'),
   path('contact/', IndexShopContactView.as_view(), name='contact'),
]

apps/login/urls.py
from django.urls import path

from .views import IndexLView

urlpatterns = [
   path('login/', IndexLView.as_view())
]

apps/shop/urls.py
from django.urls import path
from .views import ViewShop, ViewProductSingle

app_name = 'shop'


urlpatterns = [
   path('', ViewShop.as_view(), name='shop'),
   path('', ViewProductSingle.as_view(), name='product-single'),
]

apps/test_app/urls.py
from django.urls import path

from .views import RandomView

urlpatterns = [
   path('randomnumber/', RandomView.as_view()),
]

newsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('other/ ', include('apps.common.urls')),
    path('other/ ', include('apps.test_app.urls')),
    path('other/ ', include('apps.common_new.urls')),
    path('other/ ', include('apps.login.urls')),
    path('other/cart/', include('apps.cart.urls')),
    path('', include('apps.home.urls')),
    path('', include('apps.cart_shop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('checkout/', include('apps.checkout.urls')),
    path('shop/', include('apps.shop.urls')),
    path('login/', include('apps.auth_shop.urls')),
]

apps/blog/models.py
from django.db import models

# Create your models here.

apps/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Cart(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.user}"

class Wishlist(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.user}, {self.id}"

class Product(models.Model):
   name = models.CharField(max_length=255)
   price = models.DecimalField(max_digits=10, decimal_places=2)
   description = models.TextField()
   image = models.ImageField(upload_to='static/products/', null=True, blank=True)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def save(self, *args, **kwargs):
      super().save(*args, **kwargs)

      img = Image.open(self.image.path)
      img = img.resize((100, 100), Image.ANTIALIAS)
      img.save(self.image.path)

   def __str__(self):
       return self.name


class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.cart}_{self.product}"

apps/home/models.py
from django.db import models

# Create your models here.

apps/shop/models.py
from django.db import models

# Create your models here.

apps/blog/views.py
from django.shortcuts import render
from django.views import View


class ViewBlog(View):
   def get(self, request):
       return render(request, 'blog/blog.html')

class ViewBlogSingle(View):
   def get(self, request):
       return render(request, 'blog/blog-single.html')

apps/cart/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem


def view_cart(request):
   cart_items = CartItem.objects.filter(cart__user=request.user)
   total_price = sum(item.product.price * item.quantity for item in cart_items)
   context = {'cart_items': cart_items, 'total_price': total_price}
   return render(request, 'cart/cart.html', context)


def update_item(request, item_id):
   item = CartItem.objects.get(id=item_id)
   item.quantity += int(request.GET.get('quantity'))
   item.save()
   return redirect('cart:view_cart')


def remove_item(request, item_id):
   CartItem.objects.filter(id=item_id).delete()
   return redirect('cart:view_cart')


def checkout(request):
   # code to handle checkout process
   return redirect('cart:view_cart')

apps/checkout/views.py
from django.shortcuts import render
from django.views import View


class ViewCheckout(View):
   def get(self, request):
       return render(request, 'checkout/checkout.html')

apps/common/views.py
from datetime import datetime

from django.views import View
from django.http import HttpResponse

from django.shortcuts import render


class CurrentDateView(View):
   def get(self, request):
       html = f"{datetime.now()}"
       return HttpResponse(html)

class IndexView(View):
   def get(self, request):
       return render(request, 'common/index.html')

apps/home/views.py
from django.shortcuts import render
from django.views import View
from apps.cart_shop.models import Product
from apps.cart_shop.views import fill_card_in_session, fill_id_card_in_session


class IndexShopView(View):

   def get(self, request):
       fill_card_in_session(request)
       fill_id_card_in_session(request)

       data = Product.objects.all()
       context = {'data': data
                  }
       return render(request, 'home/index.html', context)


class IndexShopAboutView(View):

   def get(self, request):
       return render(request, 'home/about.html')

class IndexShopContactView(View):

   def get(self, request):
       return render(request, 'home/contact.html')

apps/login/views.py
from datetime import datetime

from django.views import View
from django.http import HttpResponse, JsonResponse

from django.shortcuts import render




class IndexLView(View):
   def get(self, request):
       return render(request, 'login/index.html')

   def post(self, request):
       return JsonResponse(request.POST, json_dumps_params={'indent': 4})

apps/shop/views.py
from django.shortcuts import render
from django.views import View


class ViewShop(View):
   def get(self, request):
       return render(request, 'shop/shop.html')

class ViewProductSingle(View):
   def get(self, request):
       return render(request, 'shop/product-single.html')

apps/test_app/views.py
from random import random
from django.views import View
from django.http import HttpResponse

random_number = random()

class RandomView(View):
   def get(self, request):
       html = f"{random()}"
       return HttpResponse(html)

apps/cart/templates/cart/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
   <table>
   <thead>
       <tr>
           <th>Product</th>
           <th>Price</th>
           <th>Pic</th>
           <th>Quantity</th>
           <th>Total</th>
           <th>Actions</th>
       </tr>
   </thead>
   <tbody>
       {% for item in cart_items %}
           <tr>
               <td>{{ item.product.name }}</td>
               <td>{{ item.product.price }}</td>
               <td><img src="{{ item.product.image.url }}" alt="{{ item.product.name }}"></td>
               <td>{{ item.quantity }}</td>
               <td>{% widthratio item.product.price 1 item.quantity %}</td>
               <td>
                   <a href="{% url 'cart:update_item' item.id %}?quantity=1">+</a>
                   <a href="{% url 'cart:update_item' item.id %}?quantity=-1">-</a>
                   <a href="{% url 'cart:remove_item' item.id %}">Remove</a>
               </td>
           </tr>
       {% endfor %}
   </tbody>
   <tfoot>
       <tr>
           <td colspan="3"></td>
           <td>Total: {{ total_price }}</td>
           <td><a href="{% url 'cart:checkout' %}">Checkout</a></td>
       </tr>
   </tfoot>
</table>
</head>
<body>

</body>
</html>

apps/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Vegefoods - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'shop/css/open-iconic-bootstrap.min.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/animate.css '%}">

    <link rel="stylesheet" href="{% static 'shop/css/owl.carousel.min.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/owl.theme.default.min.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/magnific-popup.css '%}">

    <link rel="stylesheet" href="{% static 'shop/css/aos.css '%}">

    <link rel="stylesheet" href="{% static 'shop/css/ionicons.min.css '%}">

    <link rel="stylesheet" href="{% static 'shop/css/bootstrap-datepicker.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/jquery.timepicker.css '%}">


    <link rel="stylesheet" href="{% static 'shop/css/flaticon.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/icomoon.css '%}">
    <link rel="stylesheet" href="{% static 'shop/css/style.css '%}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 1235 2355 98</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">youremail@email.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'home:index' %}">Vegefoods</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item active"><a href="{% url 'home:index' %}" class="nav-link">Home</a></li>
	          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="{% url 'shop:shop' %}">Shop</a>
              	<a class="dropdown-item" href="{% url 'cart_shop:wishlist' %}">Wishlist</a>
                <a class="dropdown-item" href="{% url 'shop:product-single' %}">Single Product</a>
                <a class="dropdown-item" href="{% url 'cart_shop:cart' %}">Cart</a>
                <a class="dropdown-item" href="{% url 'checkout:checkout' %}">Checkout</a>
              </div>
            </li>
	          <li class="nav-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	          <li class="nav-item cta cta-colored"><a href="{% url 'cart_shop:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>[{{cart_items|length}}]</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    {% block content %}

    {% endblock %}

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>



  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'shop/js/jquery.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'shop/js/popper.min.js'%}"></script>
  <script src="{% static 'shop/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'shop/js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'shop/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'shop/js/aos.js'%}"></script>
  <script src="{% static 'shop/js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'shop/js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'shop/js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'shop/js/google-map.js'%}"></script>
  <script src="{% static 'shop/js/main.js'%}"></script>

  </body>
</html>